# Generated by Django 4.0 on 2021-12-21 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kid',
            fields=[
                ('kid_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('kid_age', models.IntegerField()),
                ('parent_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter without code', regex='^\\d{10,10}$')])),
                ('parent_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
