# Generated by Django 4.0 on 2021-12-21 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='kid_age',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='kid',
            name='parent_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter without code(10 digits)', regex='^\\d{10,10}$')]),
        ),
    ]
