# Generated by Django 4.0 on 2021-12-21 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0002_alter_kid_kid_age_alter_kid_parent_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField()),
                ('Approved_by', models.CharField(editable=False, max_length=100)),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kids.kid')),
            ],
        ),
    ]
