# Generated by Django 4.0 on 2021-12-21 11:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0003_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='Group',
            field=models.CharField(choices=[('1', 'Veg'), ('2', 'Fruit'), ('3', 'Grain'), ('4', 'protein'), ('5', 'Dairy'), ('6', 'Unknown')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='Approved_by',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='updated_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
