# Generated by Django 4.0 on 2021-12-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0004_image_group_alter_image_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='Group',
            field=models.CharField(choices=[('1', 'Veg'), ('2', 'Fruit'), ('3', 'Grain'), ('4', 'protein'), ('5', 'Dairy'), ('6', 'Unknown')], max_length=20),
        ),
    ]
